services:
  music-tracker:
    image: music-tracker
    container_name: music-tracker
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - /mnt/user/appdata/music-tracker:/data
    environment:
      - DATA_PATH=/data/data.json
